APP_NAME = "AvA DB"
PORT = "port"

CLI_NAME = "CLI"
CLI_PROMPT = ">>> "
CLI_WELCOME = "AvA Database CLI. Type 'exit' to quit."
DOWNLOAD_CHUNK_SIZE = 4096

DB_TYPE_SQL = "sql"
DB_TYPE_NOSQL = "nosql"

REQUEST_KEY_TYPE = "type"
REQUEST_KEY_QUERY = "query"
REQUEST_KEY_CREATE = "create"
REQUEST_KEY_DROP = "drop"
REQUEST_KEY_DELETE = "delete"
REQUEST_KEY_UPDATE = "update"
REQUEST_KEY_INSERT= "insert"

TABLES_SUB_DIR = "tables"
METADATA_SUB_DIR = "metadata"

METADATA_TABLE_NAME_KEY = "table_name"
METADATA_FIELDS_KEY = "fields"

QUERY_OP_KEY = "op"
QUERY_VAR1_KEY = "v1"
QUERY_VAR2_KEY = "v2"
QUERY_FIELD_REF_SYM = "::"
REDUCED_COLUMN_NAME_SEP = "__"
NOSQL_LEVEL_SEP = ".."

QUERY_DESIRED_COLUMNS_KEY = "desired_columns"
QUERY_SRC_TABLE_KEY = "src_table"
QUERY_JOIN_CONDITION_KEY = "join_condition"
QUERY_JOIN_TYPE_KEY = "join_type"
QUERY_JOIN_TABLE_LEFT_KEY = "t1"
QUERY_JOIN_TABLE_RIGHT_KEY = "t2"
QUERY_ORDER_BY_KEY = "order_by"
QUERY_ORDER_BY_COLUMN_KEY = "column"
QUERY_ORDER_BY_ASC_KEY = "is_asc"
QUERY_FILTER_KEY = "row_filter"
QUERY_GROUP_BY = "group_by"

INSERT_TABLE_NAME_KEY = "table_name"
INSERT_RECORDS_KEY = "records"

CREATE_TABLE_NAME_KEY = "table_name"
DROP_TABLE_NAME_KEY = "table_name"

UPDATE_TABLE_NAME_KEY = "table_name"
UPDATE_EXPR_KEY = "expr"
UPDATE_NEW_RECORD_KEY = "record"

DELETE_TABLE_NAME_KEY = "table_name"
DELETE_EXPR_KEY = "expr"


TMP_TABLE_PREFIX = "_"

OP_NAME_NOT = "!"
OP_NAME_AND = "&&"
OP_NAME_OR = "||"
OP_NAME_LT = "<"
OP_NAME_GT = ">"
OP_NAME_LE = "<="
OP_NAME_GE = ">="
OP_NAME_EQ = "=="
OP_NAME_NE = "!="
OP_NAME_ADD = "+"
OP_NAME_SUB = "-"
OP_NAME_MUL = "*"
OP_NAME_DIV = "/"