from enum import Enum


class ErrorCode(Enum):
    OK = 0
    START_FAILED = 1
    STOP_FAILED = 2

    CALCULATE_PARAM_CNT_ERROR = 3
    CALCULATE_PARAM_TYPE_ERROR = 4

    DUPLICATED_TABLE_CREATION_REQUEST = 5

    INVALID_ARGUMENT = 6
    FILE_NOT_EXIST = 7
    UNKNOWN = 8
    UNEXPECTED_EMPTY = 9
    UNSUPPORTED = 10
    FILE_EXIST = 11
    INCONSISTENT = 12
    INTERNAL = 13
    NOT_IMPLEMENTED = 14
    TYPE_ERROR = 15
